-- Disponibilité courante d'un service par établissement (une ligne par couple).
CREATE TABLE availability (
    id           UUID PRIMARY KEY,
    facility_id  UUID NOT NULL,
    service_code TEXT NOT NULL,
    status       TEXT NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL,
    UNIQUE (facility_id, service_code)
);

CREATE INDEX idx_availability_facility ON availability (facility_id);

-- Historique auditable : une ligne conservée à chaque mise à jour.
CREATE TABLE availability_history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id  UUID NOT NULL,
    service_code TEXT NOT NULL,
    status       TEXT NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL,
    recorded_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_availability_history_facility ON availability_history (facility_id, service_code);
